- packages/platform-shared/shuvi-type-extensions-node.d.ts
- packages/platform-shared/src/node/platform/plugins/main/shuvi-app.ts
- packages/platform-web/shuvi-type-extensions-node.d.ts
- packages/platform-web/src/node/features/filesystem-routes/shuvi-app.ts
- packages/runtime/src/index.ts
- packages/service/src/core/apiTypes.ts
- packages/service/src/core/lifecycle.ts
- packages/service/src/namespace.ts
refactoring CustomCorePluginHooks
No
No
No
> chore: move CustomCorePluginHooks from shuvi/runtime to shuvi/service

- packages/service/src/core/__tests__/api.test.ts
- packages/service/src/core/paths.ts
- packages/service/src/project/__tests__/projectBuilder.test.ts
- packages/service/src/project/projectBuilder.ts
- test/fixtures/loader/tsconfig.json
- test/fixtures/model/tsconfig.json
- test/fixtures/prefetch-link/tsconfig.json
- test/fixtures/typescript/tsconfig.json
> refactor: move .shuvi/runtime to .shuvi/app/runtime

- package.json
- packages/platform-web/src/shuvi-app/react/redox-react/runtime.ts
- packages/platform-web/src/shuvi-app/react/redox-react/shuvi-app.ts
- packages/platform-web/src/shuvi-app/shuvi-runtime-index.ts
bugfix: pnpm run build error
no
no
no
> fix: build error

- packages/platform-web/src/shuvi-app/dev/webpackHotDevClient.ts
- packages/platform-web/src/shuvi-app/entry/client/app.ts
- packages/platform-web/src/shuvi-app/entry/client/run.dev.ts
- packages/service/src/core/apiTypes.ts
- packages/service/src/core/config.ts
- packages/service/src/server/middlewares/dev/devMiddleware.ts
- packages/service/src/server/middlewares/dev/hotMiddleware.ts
- packages/toolpack/src/constants.ts
- packages/toolpack/src/utils/hotDevClient/index.js
- packages/toolpack/src/utils/hotDevClient/websocket.ts
- packages/toolpack/src/webpack/plugins/module-replace-plugin/plugin.ts
Remove inactive page from HMR
no
no
no
> feat: remove inactive pages from hmr

- packages/compiler/.gitignore
- packages/compiler/src/swc/index.js
- scripts/install-native.js
fix: load swc sources path
no
no
no
> fix: load swc sources path

- packages/service/src/project/file-builder/__tests__/file-builder-watch.test.ts
- packages/service/src/project/file-builder/fileBuilder.ts
- packages/service/src/project/file-builder/types.ts
> feat(fileBuilder): file update should be skipped if content has no change

- .github/workflows/release-binary.yml
- packages/compiler-swc/crates/napi/src/bundle/mod.rs
- packages/compiler-swc/crates/napi/src/lib.rs
- packages/compiler-swc/crates/napi/src/minify.rs
- packages/compiler-swc/crates/napi/src/transform.rs
- packages/compiler-swc/package.json
- packages/compiler-swc/scripts/publish-native.js
- pnpm-lock.yaml
feature: swc release flow
no
no
no
> Feat 0801 swc flow

- .github/workflows/release-swc.yml
- package.json
- scripts/release-swc.js
feature:swc release scripts
no
no
> Feat 0803 swc release

- .github/workflows/release-swc.yml
chore: branch should from shuvi
no
no
no
> chore: branch should from shuvi

- packages/error-overlay/package.json
- packages/error-overlay/src/middleware/helper/findOriginalSourcePositionAndContent.ts
- packages/error-overlay/src/middleware/stackFrameMiddleware.ts
- pnpm-lock.yaml
> fix(overlay): part sourceMap

- packages/error-overlay/src/middleware/helper/getOriginalStackFrame.ts
- packages/error-overlay/src/middleware/helper/getSourceById.ts
- packages/error-overlay/src/middleware/stackFrameMiddleware.ts
- packages/error-overlay/src/view/helpers/nodeStackFrames.ts
- packages/error-overlay/src/view/helpers/parseStack.ts
- packages/platform-shared/src/shared/applicationTypes.ts
- packages/platform-web/src/node/features/html-render/lib/renderToHTML.ts
- packages/platform-web/src/node/features/html-render/lib/renderer/ssr.ts
- packages/platform-web/src/node/features/html-render/lib/renderer/types.ts
- packages/platform-web/src/shared/appTypes.ts
- packages/platform-web/src/shared/renderTypes.ts
- packages/platform-web/src/shuvi-app/app/client.ts
- packages/platform-web/src/shuvi-app/app/server.ts
- packages/platform-web/src/shuvi-app/helper/serializeServerError.ts
- packages/platform-web/src/shuvi-app/react/view/ReactView.client.tsx
- packages/platform-web/src/shuvi-app/react/view/ReactView.server.tsx
- packages/service/src/server/middlewares/dev/devMiddleware.ts
- packages/toolpack/src/webpack/config/node.ts
- test/e2e/custom-error.test.ts
> Feat:server render error

- packages/error-overlay/src/middleware/helper/getOriginalStackFrame.ts
- packages/error-overlay/src/middleware/stackFrameMiddleware.ts
- packages/platform-web/src/shuvi-app/react/view/ReactView.client.tsx
> refactor: optimize promise all

- packages/hook/src/__tests__/hooks/asyncSeriesBailHook.test.ts
- packages/hook/src/__tests__/hooks/asyncSeriesHook.test.ts
- packages/hook/src/__tests__/hooks/asyncSeriesWaterfallHook.test.ts
- packages/hook/src/__tests__/utils.ts
- packages/hook/src/hookGroup.ts
- packages/hook/src/hooks.ts
> feat(hook): add AsyncSeriesHook & AsyncSeriesBailHook

- packages/service/src/lib/webpack-watch-wait-for-file-builder-plugin.ts
> fix(webpack-wait-file-builder): fix clearing timer at onInvalid

- packages/error-overlay/src/client.ts
- packages/error-overlay/src/iframeScript.tsx
> fix: iframe should not be rendered when no error occurs

- packages/toolpack/src/webpack/loaders/shuvi-swc-loader/index.js
- test/e2e/loader-tree-shaking.dev.test.ts
- test/e2e/loader-tree-shaking.prod.test.ts
- test/fixtures/loader-tree-shaking/shuvi.config.js
- test/fixtures/loader-tree-shaking/src/routes/function-declaration/async/page.js
- test/fixtures/loader-tree-shaking/src/routes/function-declaration/normal/page.js
- test/fixtures/loader-tree-shaking/src/routes/variable-declaration/async/page.js
- test/fixtures/loader-tree-shaking/src/routes/variable-declaration/normal/page.js
fix: loader tree shake
yes
n
n
> fix: loader treeShake

- packages/create-shuvi/index.ts
- packages/create-shuvi/templates/default/jsconfig.json
ts prompt:
alias(add jsconfig):
> Feat:create shuvi imporve

- packages/platform-web/src/node/features/html-render/lib/getPageMiddleware.ts
- packages/platform-web/src/node/features/middlewares.ts
- packages/service/src/core/apiTypes.ts
- packages/service/src/server/shuviServer.ts
> fix(html-render): prevent `handlePageRequest` from being called repeatedly

- packages/error-overlay/src/client.ts
- packages/error-overlay/src/iframeScript.tsx
> fix: handle the errorType which is overwrited

- packages/platform-web/src/node/features/custom-server/server.ts
- packages/platform-web/src/node/features/filesystem-routes/index.ts
- test/e2e/typescript.test.ts
> feat: remove 'middleware' file convention

- packages/platform-web/package.json
- pnpm-lock.yaml
> fix: remove react-error-overlay dependency

- packages/platform-shared/src/node/platform/runtimeFiles.ts
- packages/platform-web/src/node/features/custom-server/server.ts
- packages/platform-web/src/node/features/filesystem-routes/api/apiRouteHandler.ts
- packages/platform-web/src/node/features/filesystem-routes/index.ts
- packages/platform-web/src/node/features/on-demand-compile-page/emptyComponent.ts
- packages/platform-web/src/shuvi-app/app/server.ts
- packages/platform-web/src/shuvi-app/react/view/ReactView.server.tsx
- packages/service/src/bundler/bundler.ts
- packages/service/src/bundler/typescript/getTypeScriptInfo.ts
- packages/service/src/core/api.ts
- packages/service/src/core/getPlugins.ts
- packages/service/src/server/http-server/server.ts
- packages/shuvi/src/cli.ts
- packages/shuvi/src/cmds/build.ts
- packages/shuvi/src/cmds/dev.ts
- packages/shuvi/src/cmds/serve.ts
- packages/shuvi/src/config/config.ts
- packages/shuvi/src/config/env.ts
- packages/shuvi/src/config/utils.ts
- packages/shuvi/src/tasks/build.ts
- packages/shuvi/src/utils.ts
- packages/utils/src/logger.ts
- test/utils/launcher.ts
> feat: console beautify

- packages/platform-shared/src/shared/loader/loader.ts
- packages/platform-shared/src/shared/loader/types.ts
> feat: throw error when loader return undefined

- packages/hook/src/__tests__/hooks/asyncSeriesWaterfallHook.test.ts
- packages/hook/src/__tests__/hooks/syncBailHook.test.ts
- packages/hook/src/__tests__/hooks/syncHook.test.ts
- packages/hook/src/__tests__/hooks/syncWaterfallHook.test.ts
- packages/hook/src/hooks.ts
> fix(hook): seriesHook should discard handlers that returns undefined

- packages/create-shuvi/create-app.ts
> fix: replace start with serve

- packages/platform-shared/src/node/project/file-presets/files/app/user/error.js.ts
- packages/platform-shared/src/node/route/helpers.ts
- packages/platform-web/src/node/features/filesystem-routes/index.ts
- packages/platform-web/src/node/features/filesystem-routes/page/routes.ts
- packages/utils/src/__tests__/file.test.ts
- packages/utils/src/file.ts
feat: remove ext
yes
no
page component remove ext
> feat: remove ext

- packages/platform-web/src/node/features/model/index.ts
- packages/platform-web/src/node/targets/react/model/index.ts
bugfix: add redoxReact alias
no
no
no
> fix(platform-web): redoxReact alias

- packages/compiler-swc/crates/core/src/shuvi_page.rs
- packages/compiler-swc/crates/core/tests/fixture/shuvi-page/side-effects/default.js
- packages/compiler-swc/crates/core/tests/fixture/shuvi-page/side-effects/input.js
- packages/compiler-swc/crates/core/tests/fixture/shuvi-page/side-effects/loader.js
fix(swc): remove effects
yes
no
no
> fix(swc): remove effects

- packages/compiler/package.json
- packages/platform-shared/package.json
- packages/platform-shared/shuvi-type-extensions-node.d.ts
- packages/platform-shared/src/node/platform/shuvi-type-extensions-node.ts
- packages/platform-shared/src/shared/runtimeConfigTypes.ts
- packages/platform-shared/tsconfig.build.node.json
- packages/platform-web/package.json
> fix: rename exported shuvi-type-extensions files

- packages/service/src/server/middlewares/getAssetMiddleware.ts
> fix: add catch for asset middleware

- packages/service/src/bundler/bundler.ts
- packages/service/src/bundler/index.ts
- packages/service/src/core/api.ts
- packages/service/src/index.ts
- packages/service/src/server/index.ts
- packages/service/src/server/middlewares/dev/devMiddleware.ts
- packages/service/src/server/middlewares/getAssetMiddleware.ts
- packages/service/src/server/shuviDevServer.ts
- packages/service/src/server/shuviServerTypes.ts
- packages/shuvi/src/tasks/build.ts
- pnpm-lock.yaml
- test/e2e/public-dir.test.ts
- test/utils/launcher.ts
- test/utils/package.json
> feat: always host public files no matter what environment and public path are

- packages/service/src/server/http-server/__tests__/server.test.ts
- packages/service/src/server/http-server/router.ts
- packages/service/src/server/http-server/server.ts
- packages/service/src/server/shuviDevServer.ts
feat(service): catch unhandledRejection
no
no
no
> feat(service): catch unhandledRejection

- packages/platform-web/src/shuvi-app/app/server.ts
- packages/router/src/__tests__/router.test.ts
- packages/router/src/history/base.ts
- packages/router/src/history/memory.ts
- packages/router/src/router.ts
- packages/router/src/types/router.ts
- test/e2e/loader.test.ts
- test/fixtures/loader/src/routes/context/redirect/combo/a/page.tsx
- test/fixtures/loader/src/routes/context/redirect/combo/b/page.tsx
- test/fixtures/loader/src/routes/context/redirect/combo/c/page.tsx
> feat(router): add skipGuards option for push/replace & fix loader redirect issue

- packages/platform-shared/src/shared/loader/loader.ts
- packages/platform-web/src/shuvi-app/app/client.ts
- packages/platform-web/src/shuvi-app/app/server.ts
- packages/platform-web/src/shuvi-app/helper/isThirdSite.ts
- packages/platform-web/src/shuvi-app/react/view/ReactView.server.tsx
- packages/router/src/router.ts
- packages/router/src/types/router.ts
- test/e2e/loader.test.ts
- test/fixtures/loader/src/routes/context/redirect/combo/$d/page.tsx
- test/fixtures/loader/src/routes/context/redirect/combo/b/page.tsx
- test/fixtures/loader/src/routes/context/redirect/page.tsx
feat(platform-web): redirect support thirdy-party sites
yes
no
redirect support thirdy-party sites
> feat(platform-web): redirect support thirdy-party sites

- packages/platform-web/src/node/features/html-render/index.ts
- packages/service/src/bundler/bundler.ts
- packages/service/src/bundler/config.ts
- packages/toolpack/src/webpack/config/base.ts
- packages/toolpack/src/webpack/config/browser.ts
- packages/toolpack/src/webpack/config/node.ts
- packages/toolpack/src/webpack/config/parts/__tests__/helpers.test.ts
- packages/toolpack/src/webpack/config/parts/helpers.ts
- pnpm-lock.yaml
- test/e2e/loader.test.ts
- test/e2e/plugin-and-preset.test.ts
- test/fixtures/plugin-and-preset/package.json
- test/fixtures/plugin-and-preset/plugin/index.js
- test/fixtures/plugin-and-preset/src/routes/node-external/page.js
fix(service): fix external helper
yes
no
fix(service): fix external helper bug
> fix(service): fix external helper

- packages/compiler-swc/crates/core/src/shuvi_page.rs
- packages/compiler-swc/crates/core/tests/fixture/shuvi-page/should-not-remove-depends-components/default.js
- packages/compiler-swc/crates/core/tests/fixture/shuvi-page/should-not-remove-depends-components/input.js
- packages/compiler-swc/crates/core/tests/fixture/shuvi-page/should-not-remove-depends-components/loader.js
- packages/compiler-swc/crates/core/tests/fixture/shuvi-page/should-not-remove-import-with-same-depends/default.js
- packages/compiler-swc/crates/core/tests/fixture/shuvi-page/should-not-remove-import-with-same-depends/input.js
- packages/compiler-swc/crates/core/tests/fixture/shuvi-page/should-not-remove-import-with-same-depends/loader.js
> fix(swc): page and loader has same depends

- packages/toolpack/src/webpack/config/base.ts
> feat: disable spiltChunks at dev to prevent preload error

- packages/service/src/core/api.ts
- packages/telemetry/src/helper/anonymous-meta.ts
> fix: add meta info and fix get telemetry logic

- packages/compiler-swc/crates/core/tests/fixture/shuvi-page/should-not-remove-depends-components/default.js
- packages/compiler-swc/crates/core/tests/fixture/shuvi-page/should-not-remove-import-with-same-depends/default.js
fix(swc): page tree shake error
no
no
no
> chore: update code style

- packages/service/src/core/__tests__/getPlugins.test.ts
- packages/service/src/core/getPlugins.ts
- packages/service/src/project/file-presets/files/app/shuvi-app.d.ts.ts
> fix(plugin): fix output result of typeDeclarationFiles

- packages/platform-shared/src/shared/loader/loader.ts
- packages/platform-shared/src/shared/loader/types.ts
- packages/platform-web/src/shuvi-app/app/client.ts
- packages/platform-web/src/shuvi-app/app/server.ts
- test/e2e/loader.test.ts
- test/fixtures/loader/src/routes/layout.tsx
…me at different layers of route
> fix(loader): pathname, query and params at loaderContext should be same at different layers of route

- packages/service/src/project/file-utils/utils.ts
> fix: remove extension of exports in @shuvi/app/user

- packages/telemetry/src/telemetry.ts
> chore: fix flush async function

- packages/platform-web/src/node/targets/react/bundler/index.ts
- test/e2e/webpack-watch-wait-file-builder.test.ts
- test/fixtures/plugin-and-preset/package.json
- test/fixtures/spa/package.json
> fix: fix the logic of resolveUser to adapt to monorepo

- packages/platform-web/src/shuvi-app/model/runtime.ts
feat: doura support devtool
no
no
no
> feat: doura support devtool

- packages/platform-web/src/shuvi-app/dev/hotDevClient.ts
- packages/service/package.json
- packages/service/src/core/api.ts
- packages/service/src/server/middlewares/dev/hotMiddleware.ts
- packages/trace/package.json
- packages/trace/src/index.ts
- packages/trace/src/report/index.ts
- packages/trace/src/report/to-json.ts
- packages/trace/src/report/to-telemetry.ts
- packages/trace/src/shared.ts
- packages/trace/src/trace.ts
- packages/trace/tsconfig.build.json
- packages/trace/tsconfig.json
- pnpm-lock.yaml
> feat: init the trace module and add hmr event to json and telemetry

- packages/platform-web/src/shuvi-app/app/client.ts
- test/e2e/hmr.test.ts
> fix: hmr error

- packages/trace/src/report/to-telemetry.ts
> chore: add SHUVI prefix to CLIENT_HMR_LATENCY

- packages/platform-web/src/node/features/html-render/lib/generateFilesByRoutId.ts
- packages/platform-web/src/node/features/html-render/lib/webpack/build-manifest-plugin.ts
- packages/platform-web/src/shared/htmlRenderer.ts
fix: loadble props may not exist
no
no
no
> fix: loadble props may not exist

- packages/service/src/server/middlewares/dev/hotMiddleware.ts
> cohre: fix precision

- packages/service/src/analysis/events/build.ts
- packages/service/src/bundler/config.ts
- packages/service/src/core/apiTypes.ts
- test/fixtures/compiler/jsconfig.json
- test/fixtures/compiler/shuvi.config.js
> feat: set `experimentalDecorators` and `emitDecoratorMetadata` via tsconfig

- packages/platform-shared/shuvi-type-extensions-runtime.d.ts
- packages/platform-shared/src/shared/__tests__/application.test.ts
- packages/platform-shared/src/shared/application.ts
- packages/platform-shared/src/shared/applicationTypes.ts
- packages/platform-shared/src/shared/loader/loader.ts
- packages/platform-shared/src/shuvi-app/application.bare.ts
- packages/platform-shared/src/shuvi-app/application.ts
- packages/platform-web/shuvi-type-extensions-runtime.d.ts
- packages/platform-web/src/shuvi-app/app/client.ts
- packages/platform-web/src/shuvi-app/app/server.ts
- test/e2e/loader-tree-shaking.test.ts
- test/e2e/tree-shaking.test.ts
> perfomance: split loaders into a separated chunk

- packages/toolpack/src/webpack/loaders/shuvi-swc-loader/index.ts
> chore: page-loader not warp react-refresh

- packages/platform-web/src/shuvi-app/react/view/ReactView.client.tsx
> fix: client remove overlay

- package.json
- packages/platform-shared/src/node/route/route.ts
- pnpm-lock.yaml
- test/utils/package.json
> fix: fix parameters of `getRawRoutesFromDir`

- packages/service/src/bundler/config.ts
- packages/toolpack/src/webpack/config/base.ts
- packages/toolpack/src/webpack/config/browser.ts
- test/e2e/shuvi-cli.test.ts
> feat(analyze): apply analyzer to all targets & add webpack stats output

- packages/router/src/__tests__/router.test.ts
- packages/router/src/router.ts
chore: useRouter support Destructuring 
no
no
no
> chore: useRouter support Destructuring

- packages/service/src/config/__tests__/config.test.ts
- packages/service/src/config/__tests__/utils.ts
- packages/service/src/config/config.ts
- packages/service/src/core/api.ts
- packages/shuvi/src/shuvi.ts
- packages/shuvi/src/tasks/build.ts
> feat: allow configFile set to false to skip reading shuvi config file

- packages/error-overlay/src/client.ts
- packages/platform-web/src/shuvi-app/dev/hotDevClient.ts
feature: Continuous errors and no errors will not operate dom
no
no
no
> chore: optimization error-overlay

- packages/platform-shared/src/shared/applicationTypes.ts
- packages/platform-shared/src/shared/models/error.ts
- packages/platform-web/src/shuvi-app/app/client.ts
- packages/platform-web/src/shuvi-app/helper/serializeServerError.ts
- packages/platform-web/src/shuvi-app/react/AppContainer.tsx
- packages/platform-web/src/shuvi-app/react/Error.tsx
- packages/platform-web/src/shuvi-app/react/ErrorBoundary.tsx
- packages/platform-web/src/shuvi-app/react/ErrorPage.tsx
- packages/platform-web/src/shuvi-app/react/view/ReactView.client.tsx
- packages/shared/src/constants.ts
- test/e2e/custom-error.test.ts
- test/e2e/error.test.ts
- test/fixtures/custom-error/src/error.js
- test/fixtures/custom-error/src/routes/render-error/page.jsx
- test/fixtures/default-error/shuvi.config.js
- test/fixtures/default-error/src/routes/loader-error/page.jsx
- test/fixtures/default-error/src/routes/page.jsx
- test/fixtures/default-error/src/routes/render-error/page.jsx
- custom error page 的props中增加一个字段  error, 存储原始的对象
- application内置error格式调整为
- message: 展示错误的字符串，等同于error page中的errorDesc
- code：错误码，等同于error page中的errorCode
- error: 原始错误实例，等同于error page中的error
- client 端默认报错message (errorDesc)统一为 Internal Application Error
- server 端默认报错message (errorDesc)统一为 Internal Server Error
- 只有使用loader的error 返回值，才能修改报错message（errorDesc）
- client 端运行的loader，返回error时，会去掉statusCode（因为没有意义
- custom error page 中，可以判断是否有code，来判断是serve端还是client端（对标旧版next.js
> feat: optimize error page logic

- packages/eslint-plugin-shuvi/src/__tests__/no-head-element.test.ts
- packages/eslint-plugin-shuvi/src/__tests__/no-html-link-for-pages.test.ts
- packages/eslint-plugin-shuvi/src/rules/no-head-element.js
- packages/eslint-plugin-shuvi/src/rules/no-html-link-for-pages.js
- packages/shuvi/src/commands/eslint/core/customFormatter.ts
- packages/shuvi/src/commands/eslint/core/runLintCheck.ts
chore: update eslint link
no
no
no
> chore: update eslint link

- packages/hook/src/__tests__/hookGroup.ts/hookGroup.test.ts
- packages/hook/src/hookGroup.ts
- packages/hook/src/index.ts
- packages/hook/src/types.ts
- packages/hook/src/utils.ts
- packages/platform-web/src/node/targets/react/model/index.ts
- packages/shared/src/plugins.ts
- test/e2e/webpack-watch-wait-file-builder.test.ts
> feat: fix hookGroup options

- packages/eslint-config-shuvi/index.js
- packages/eslint-config-shuvi/package.json
- packages/eslint-plugin-shuvi/src/__tests__/no-typos-custom-app.test.ts
- packages/eslint-plugin-shuvi/src/__tests__/no-typos-custom-server.test.ts
- packages/eslint-plugin-shuvi/src/__tests__/no-typos-page.test.ts
- packages/eslint-plugin-shuvi/src/index.ts
- packages/eslint-plugin-shuvi/src/rules/no-typos-custom-app.js
- packages/eslint-plugin-shuvi/src/rules/no-typos-custom-server.js
- packages/eslint-plugin-shuvi/src/rules/no-typos-page.js
- packages/eslint-plugin-shuvi/src/utils/url.ts
- pnpm-lock.yaml
- test/e2e/cli.test.ts
- test/fixtures/eslint/.eslintrc.json
- test/fixtures/eslint/package.json
- test/fixtures/eslint/shuvi.config.js
- test/fixtures/eslint/src/app.js
- test/fixtures/eslint/src/routes/other/page.js
- test/fixtures/eslint/src/routes/page.js
- test/fixtures/eslint/src/server.js
- test/utils/shuvi.ts
feat: add more lint rules
Y
N
N
> feat: add more lint rules

- test/e2e/cli.test.ts
> chore: eslint test

- packages/router-react/src/__tests__/__snapshots__/nested-params.test.js.snap
- packages/router-react/src/__tests__/nested-params.test.js
- packages/router-react/src/hooks.tsx
> fix: `useParams` will give the same result no matter where it is used

- packages/platform-web/src/shuvi-app/react/view/ReactView.server.tsx
- pnpm-lock.yaml
- test/e2e/custom-routes.test.ts
- test/fixtures/custom-routes/package.json
- test/fixtures/custom-routes/shuvi.config.js
- test/fixtures/custom-routes/src/routes/about/page.js
- test/fixtures/custom-routes/src/routes/layout.js
- test/fixtures/custom-routes/src/routes/page.js
fix: custom routes redirect
Y
N
N
> fix: custom routes redirect

- packages/error-overlay/src/client.ts
Overlay iframe may cover the entire webpage, resulting in invalid clicks
rever: [optimization error-overlay](https://github.com/shuvijs/shuvi/pull/515/files)
N
N
N
> rever: optimization error-overlay

- packages/platform-web/src/node/features/html-render/lib/webpack/build-manifest-plugin.ts
- packages/toolpack/src/webpack/config/browser.ts
> fix: keep the default cacheGroups settings

- packages/platform-web/src/shuvi-app/dev/hotDevClient.ts
bugfix: hmr client 404 error
no
no
no
> fix: hmr request 404

- test/fixtures/loader-tree-shaking/README.md
> docs: record loader treeShake issue

- packages/shuvi/src/commands/eslint/options.ts
- packages/shuvi/src/commands/lint.ts
fix(lint): accept options starting with --no
no
no
> fix(lint): accept options starting with --no

- packages/eslint-plugin-shuvi/src/__tests__/no-export-loader-default-from-same-module.test.ts
- packages/eslint-plugin-shuvi/src/index.ts
- packages/eslint-plugin-shuvi/src/rules/no-export-loader-default-from-same-module.js
- packages/eslint-plugin-shuvi/src/rules/no-typos-page.js
- packages/eslint-plugin-shuvi/src/utils/is-page.ts
feat: add loader default rule
Yes
no
none
> feat: add loader default rule

- packages/platform-web/src/node/features/filesystem-routes/api/middleware.ts
- packages/platform-web/src/node/features/filesystem-routes/middleware/middleware.ts
- packages/service/src/server/http-server/router.ts
- packages/service/src/server/middlewares/getAssetMiddleware.ts
- packages/service/src/server/plugin.ts
- packages/service/src/server/shuviServer.ts
- packages/service/src/server/trace.ts
- packages/shared/src/constants/trace.ts
…VER_RUN_MIDDLEWARE_ROUTES and SHUVI_SERVER_RUN_API_MIDDLEWARE
> feat: add metrics point: SHUVI_SERVER_RUN_ASSET_MIDDLEWARE, SHUVI_SERVER_RUN_MIDDLEWARE_ROUTES and SHUVI_SERVER_RUN_API_MIDDLEWARE

- packages/platform-web/src/node/features/filesystem-routes/api/middleware.ts
- packages/platform-web/src/node/features/filesystem-routes/middleware/middleware.ts
- packages/platform-web/src/node/features/html-render/lib/getPageMiddleware.ts
- packages/platform-web/src/node/features/html-render/lib/renderToHTML.ts
- packages/platform-web/src/node/features/html-render/lib/renderer/ssr.ts
- packages/platform-web/src/node/features/html-render/serverHooks.ts
- packages/platform-web/src/shared/appTypes.ts
- packages/platform-web/src/shared/renderTypes.ts
- packages/platform-web/src/shuvi-app/app/server.ts
- packages/platform-web/src/shuvi-app/react/view/ReactView.server.tsx
- packages/service/package.json
- packages/service/src/server/http-server/router.ts
- packages/service/src/server/http-server/server.ts
- packages/service/src/server/http-server/serverTypes.ts
- packages/service/src/server/middlewares/getAssetMiddleware.ts
- packages/service/src/server/plugin.ts
- packages/service/src/server/trace.ts
- packages/service/src/trace/index.ts
- packages/shared/src/constants/trace.ts
- pnpm-lock.yaml
> chore: trace add requestId

- packages/platform-web/src/node/features/filesystem-routes/api/middleware.ts
- packages/platform-web/src/node/features/filesystem-routes/middleware/middleware.ts
- packages/platform-web/src/node/features/html-render/lib/getPageMiddleware.ts
- packages/platform-web/src/node/features/html-render/lib/renderToHTML.ts
- packages/platform-web/src/shuvi-app/app/server.ts
- packages/platform-web/src/shuvi-app/react/view/ReactView.server.tsx
- packages/service/src/server/http-server/router.ts
- packages/service/src/server/middlewares/getAssetMiddleware.ts
- packages/service/src/server/trace.ts
- packages/shared/src/constants/trace.ts
> chore: update trace attrs requestId

- packages/platform-web/src/node/features/filesystem-routes/page/__tests__/routes.test.ts
- packages/platform-web/src/node/features/filesystem-routes/page/routes.ts
- packages/platform-web/src/node/features/html-render/lib/generateFilesByRoutId.ts
- packages/platform-web/src/shuvi-app/react/Link.tsx
- test/e2e/prefetch-link.test.ts
- test/fixtures/prefetch-link/src/routes/foo/foo-2/page.tsx
- test/fixtures/prefetch-link/src/routes/foo/layout.tsx
- test/fixtures/prefetch-link/src/routes/layout.tsx
> feat: Update chunk naming rules and fix generateFilesByRoutId bug

- packages/toolpack/src/webpack/config/base.ts
- packages/toolpack/src/webpack/config/browser.ts
- packages/toolpack/src/webpack/config/node.ts
- packages/toolpack/src/webpack/config/parts/helpers.ts
> fix(webpack): use default splitChunks for server bundle

- packages/platform-web/src/shuvi-app/app/client.ts
- packages/platform-web/src/shuvi-app/app/server.ts
- packages/router/src/__tests__/router.test.ts
- packages/router/src/history/base.ts
- packages/router/src/router.ts
- packages/router/src/types/history.ts
- packages/router/src/utils/history.ts
- test/e2e/loader.test.ts
- test/fixtures/loader/shuvi.config.ts
- test/fixtures/loader/src/routes/page.tsx
This fixes https://github.com/shuvijs/shuvi/issues/563
> fix: fix wrong history when using client side loader redirect

- .github/workflows/ci.yml
- .github/workflows/release-swc.yml
- package.json
- pnpm-lock.yaml
> chore: upgrade pnpm to 8.9.2

- packages/platform-shared/src/shared/helper/getAppData.ts
- packages/platform-web/src/node/features/html-render/lib/renderToHTML.ts
- packages/platform-web/src/node/features/html-render/lib/renderer/ssr.ts
- packages/platform-web/src/node/features/on-demand-compile-page/onDemandRouteManager.ts
- packages/platform-web/src/node/shuvi-type-extensions-node.ts
- packages/platform-web/src/shared/appTypes.ts
- packages/platform-web/src/shuvi-app/app/client.ts
- packages/platform-web/src/shuvi-app/app/server.ts
- packages/router/src/router.ts
- packages/router/src/types/router.ts
- packages/service/src/server/middlewares/setupAppConfigMiddleware.ts
- packages/service/src/server/plugin.ts
- packages/service/src/server/shuviDevServer.ts
- packages/service/src/server/shuviProdServer.ts
- pnpm-lock.yaml
- test/e2e/basename.test.ts
- test/fixtures/basename/package.json
- test/fixtures/basename/plugin/server.js
- test/fixtures/basename/shuvi.config.js
- test/fixtures/basename/src/routes/$lng/page.js
- test/fixtures/basename/src/routes/layout.js
- test/fixtures/basename/src/routes/page.js
> feat: add runtime basename config

- packages/platform-web/src/node/features/filesystem-routes/hooks.ts
- packages/platform-web/src/node/features/html-render/serverHooks.ts
- packages/platform-web/src/node/features/middlewares.ts
- packages/platform-web/src/node/features/setup-app-config/index.ts
- packages/platform-web/src/node/shuvi-runtime-server.ts
- packages/service/src/server/plugin.ts
- packages/service/src/server/shuviDevServer.ts
- packages/service/src/server/shuviProdServer.ts
> feat: move setupAppConfigMiddleware to platform-web

- packages/platform-shared/src/shuvi-app/application.ts
- packages/platform-web/src/node/features/custom-server/server.ts
> feat: add plugin name for shuvi-user-app and shuvi-user-server

- .github/workflows/ci.yml
matrix testing for node.js 16 and 20
> ci: add matrix testing for node.js 16 and 20

- packages/toolpack/src/webpack/config/browser.ts
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/817#issuecomment-1697748033
> fix: fork-ts-checker-webpack-plugin options breaking changes

- examples/basic/.eslintrc.json
- examples/basic/package.json
- packages/shuvi/src/commands/eslint/options.ts
- packages/shuvi/src/commands/utils/__tests__/collectArrayOptions.test.ts
- packages/shuvi/src/commands/utils/collectArrayOptions.ts
- pnpm-lock.yaml
> fix: shuvi lint --file should work now

- pnpm-lock.yaml
- test/e2e/typeof-window.test.ts
- test/fixtures/basic/package.json
- test/fixtures/basic/src/routes/esmodule/page.jsx
> test: add e2e test that webpack should remove 'typeof window' dead code.
